# Generated by Django 6.0 on 2025-12-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='prix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'offre de marché',
                'verbose_name_plural': 'offres de marché',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('awaiting_payment', 'En attente de paiement'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=32, verbose_name='statut')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='id externe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'dépôt',
                'verbose_name_plural': 'dépôts',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='XAF', max_length=10, verbose_name='devise')),
                ('available', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='disponible')),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='en attente')),
                ('gains', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='gains')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'portefeuille',
                'verbose_name_plural': 'portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant')),
                ('type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('trade', 'Échange')], max_length=20, verbose_name='type de transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet', verbose_name='portefeuille')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
