# Generated by Django 6.0 on 2025-12-24 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='téléphone')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='total investi')),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='valeur du portefeuille')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investisseur',
                'verbose_name_plural': 'investisseurs',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
