# Generated by Django 6.0 on 2025-12-24 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investor_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketoffer',
            name='price',
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='montant demandé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire à'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='price_offered',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='prix offert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_offers', to=settings.AUTH_USER_MODEL, verbose_name='vendeur'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='source',
            field=models.CharField(default='virtual', max_length=32, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('accepted', 'Accepté'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='open', max_length=32, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='surplus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='surplus'),
        ),
        migrations.AlterField(
            model_name='marketoffer',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('trade', 'Échange'), ('referral', 'Parrainage')], max_length=20, verbose_name='type de transaction'),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL, verbose_name='parrain')),
            ],
            options={
                'verbose_name': 'code de parrainage',
                'verbose_name_plural': 'codes de parrainage',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='pending', max_length=32, verbose_name='statut')),
                ('meta', models.JSONField(blank=True, null=True, verbose_name='meta')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='filleul')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='api.referralcode', verbose_name='code')),
            ],
            options={
                'verbose_name': 'parrainage',
                'verbose_name_plural': 'parrainages',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='api.referral', verbose_name='parrainage')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'récompense de parrainage',
                'verbose_name_plural': 'récompenses de parrainage',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=128, verbose_name='offer id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant demandé')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='prix offert')),
                ('surplus', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='surplus')),
                ('buyer_info', models.JSONField(blank=True, null=True, verbose_name='acheteur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='vendeur')),
            ],
            options={
                'verbose_name': 'trade',
                'verbose_name_plural': 'trades',
            },
        ),
    ]
