# Generated by assistant: add sale_balance to Wallet
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_marketoffer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='sale_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='solde de vente'),
        ),
    ]
