# Generated by Django 6.0 on 2026-01-01 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_sale_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='invested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='solde investi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('trade', 'Échange'), ('referral', 'Parrainage'), ('transfer', 'Transfert')], max_length=20, verbose_name='type de transaction'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='CDF', max_length=10, verbose_name='devise'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant investi')),
                ('daily_rate', models.DecimalField(decimal_places=6, default=0.025, max_digits=10, verbose_name='taux journalier')),
                ('last_accrual', models.DateTimeField(blank=True, null=True, verbose_name='dernière capitalisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='api.wallet', verbose_name='portefeuille')),
            ],
            options={
                'verbose_name': 'investissement',
                'verbose_name_plural': 'investissements',
            },
        ),
    ]
