# Generated by Django 6.0 on 2026-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wallet_invested_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='vip_level',
            field=models.IntegerField(default=0, verbose_name='niveau VIP'),
        ),
        migrations.AddField(
            model_name='investor',
            name='vip_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP depuis'),
        ),
    ]
