# Generated by Django 6.0 on 2026-01-02 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_investor_vip_level_investor_vip_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='intérêts accumulés'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdraw', 'Retrait'), ('trade', 'Échange'), ('referral', 'Parrainage'), ('transfer', 'Transfert'), ('interest', 'Intérêt'), ('encash', 'Encaissement')], max_length=20, verbose_name='type de transaction'),
        ),
        migrations.CreateModel(
            name='HiddenOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_until', models.DateTimeField(verbose_name="masqué jusqu'à")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_entries', to='api.marketoffer', verbose_name='offre')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hidden_offers', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'offre masquée',
                'verbose_name_plural': 'offres masquées',
            },
        ),
    ]
