# Generated by Django 6.0 on 2026-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_investment_accrued_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USDT', max_length=10, verbose_name='devise'),
        ),
    ]
