# Generated by Django 6.0.1 on 2026-01-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_wallet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketoffer',
            name='surplus',
        ),
    ]
