# Generated by Django 6.0.1 on 2026-01-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_marketoffer_surplus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketoffer',
            name='seller',
        ),
    ]
