# Generated by Django 6.0.1 on 2026-01-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_marketoffer_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketoffer',
            name='amount_requested',
        ),
    ]
