# Generated by Django 6.0.1 on 2026-01-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_marketoffer_amount_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketoffer',
            name='source',
        ),
    ]
