# Generated by Django 6.0.1 on 2026-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_marketoffer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketoffer',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('close', 'fermé')], default='open', max_length=32, verbose_name='statut'),
        ),
    ]
