# Generated by Django 6.0.1 on 2026-01-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_marketoffer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4'), (5, 'Niveau 5'), (6, 'Niveau 6'), (7, 'Niveau 7'), (8, 'Niveau 8'), (9, 'Niveau 9'), (10, 'Niveau 10'), (11, 'Niveau 11'), (12, 'Niveau 12')], unique=True, verbose_name='niveau')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='titre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='prix')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pourcentage')),
                ('daily_gains', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='gains quotidiens')),
                ('delay_days', models.IntegerField(default=0, verbose_name='délai en jours')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'niveau VIP',
                'verbose_name_plural': 'niveaux VIP',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserVIPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='acheté le')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('vip_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.viplevel', verbose_name='niveau VIP')),
            ],
            options={
                'verbose_name': 'souscription VIP',
                'verbose_name_plural': 'souscriptions VIP',
                'unique_together': {('user', 'vip_level')},
            },
        ),
    ]
