# Generated by Django 6.0.1 on 2026-01-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_viplevel_uservipsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_agent', models.CharField(max_length=20, unique=True, verbose_name="numéro de l'agent")),
                ('nom_agent', models.CharField(max_length=100, verbose_name="nom de l'agent")),
                ('operateur', models.CharField(choices=[('orange', 'Orange'), ('airtel', 'Airtel'), ('mpesa', 'M-Pesa')], max_length=20, verbose_name='opérateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
            ],
            options={
                'verbose_name': 'opérateur',
                'verbose_name_plural': 'opérateurs',
                'unique_together': {('numero_agent', 'operateur')},
            },
        ),
    ]
