# Generated by Django 6.0.1 on 2026-01-30 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_operateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', 'Banque'), ('operator', 'Opérateur')], max_length=20, verbose_name='type de compte')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom de la banque')),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="nom de l'opérateur")),
                ('account_number', models.CharField(max_length=100, verbose_name='numéro de compte')),
                ('account_holder_name', models.CharField(max_length=200, verbose_name='nom du titulaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='compte par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'compte bancaire utilisateur',
                'verbose_name_plural': 'comptes bancaires utilisateurs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
