# Generated by Django 6.0.1 on 2026-01-31 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userbankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant')),
                ('bank', models.CharField(max_length=100, verbose_name='banque/opérateur')),
                ('account', models.CharField(max_length=100, verbose_name='numéro de compte')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Complétée'), ('rejected', 'Rejetée')], default='pending', max_length=32, verbose_name='statut')),
                ('reason_rejected', models.TextField(blank=True, null=True, verbose_name='raison du rejet')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'demande de retrait',
                'verbose_name_plural': 'demandes de retrait',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait')], max_length=20, verbose_name='type de notification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='montant')),
                ('account_info', models.CharField(max_length=255, verbose_name='info compte')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='api.deposit', verbose_name='dépôt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='api.withdrawal', verbose_name='retrait')),
            ],
            options={
                'verbose_name': 'notification administrateur',
                'verbose_name_plural': 'notifications administrateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
