# Generated by Django 6.0.1 on 2026-01-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_withdrawal_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('TRC20_USDT', 'TRC-20 (USDT)'), ('BEP20_USDT', 'BEP-20 (USDT)'), ('BNB', 'BNB (Binance Smart Chain)')], max_length=20, unique=True, verbose_name='réseau')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'adresse crypto',
                'verbose_name_plural': 'adresses crypto',
                'ordering': ['network'],
            },
        ),
    ]
