# Generated by Django 6.0.1 on 2026-01-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sociallinks'),
        ('api', '0018_cryptoaddress'),
    ]

    operations = [
    ]
