# Generated by Django 6.0.1 on 2026-01-31 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_0014_sociallinks_0018_cryptoaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de modification'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('withdrawal_approved', 'Retrait Approuvé'), ('withdrawal_rejected', 'Retrait Rejeté'), ('deposit_approved', 'Dépôt Approuvé'), ('deposit_rejected', 'Dépôt Rejeté'), ('general', 'Général')], max_length=30, verbose_name='type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='api.deposit', verbose_name='dépôt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='api.withdrawal', verbose_name='retrait')),
            ],
            options={
                'verbose_name': 'notification utilisateur',
                'verbose_name_plural': 'notifications utilisateur',
                'ordering': ['-created_at'],
            },
        ),
    ]
