# Generated by Django 6.0.1 on 2026-02-01 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_sociallinks_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='first_deposit_reward_processed',
            field=models.BooleanField(default=False, verbose_name='première commission versée'),
        ),
        migrations.AddField(
            model_name='referral',
            name='generation',
            field=models.IntegerField(choices=[(1, 'Génération 1 (Parent)'), (2, 'Génération 2 (Enfant)'), (3, 'Génération 3 (Petit-enfant)')], default=1, verbose_name='génération'),
        ),
        migrations.AddField(
            model_name='referral',
            name='parent_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_referrals', to='api.referral', verbose_name='parrainage parent'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposit', verbose_name='dépôt'),
        ),
        migrations.AddField(
            model_name='referralreward',
            name='reward_type',
            field=models.CharField(choices=[('direct_generation1', 'Commission directe - Génération 1 (10%)'), ('direct_generation2', 'Commission directe - Génération 2 (10%)'), ('indirect_generation2', 'Commission indirecte - Génération 2 (3%)')], default='direct_generation1', max_length=30, verbose_name='type de commission'),
        ),
    ]
