# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_referral_first_deposit_reward_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='sous-titre')),
                ('historique', models.TextField(blank=True, verbose_name='historique')),
                ('mission', models.TextField(blank=True, verbose_name='mission')),
                ('vision', models.TextField(blank=True, verbose_name='vision')),
                ('values', models.TextField(blank=True, verbose_name='valeurs')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='année de création')),
                ('headquarters', models.CharField(blank=True, max_length=200, verbose_name='siège')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone de contact')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
            ],
            options={
                'verbose_name': 'À propos',
                'verbose_name_plural': 'À propos',
            },
        ),
    ]
