# Generated by Django 4.2.7 on 2026-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_create_userbankaccount_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservipsubscription',
            name='contract_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin du contrat'),
        ),
        migrations.AddField(
            model_name='uservipsubscription',
            name='contract_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='début du contrat'),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reward_type',
            field=models.CharField(choices=[('direct_generation1', 'Commission directe - Génération 1 (10%)'), ('indirect_generation2', 'Commission indirecte - Génération 2 (3%)'), ('indirect_generation3', 'Commission indirecte - Génération 3 (1%)')], default='direct_generation1', max_length=30, verbose_name='type de commission'),
        ),
    ]
