# Generated by Django 4.2.7 on 2026-02-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_uservipsubscription_contract_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='market_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='api.marketoffer', verbose_name='offre du marché'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='contrat_duree',
            field=models.PositiveIntegerField(default=30, verbose_name='durée du contrat (jours)'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='gains',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='gains quotidiens'),
        ),
    ]
